Description: This template contains the security groups and networks access list.

Resources:
  SonarqubeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: dso-ipic-networking-sonarqube-sg-private
      VpcId: !ImportValue RDS-VPCId
      GroupDescription: Common SG for vpc Sonarqube
      SecurityGroupIngress:
        - CidrIp: "{{resolve:ssm:/config/infra/devops/ecs/vpc-cidr}}"
          IpProtocol: -1
        - CidrIp: "{{resolve:ssm:/config/infra/rds/vpc-cidr}}"
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: dso-ipic-networking-sonarqube-sg-private
        - Key: ORGANIZATION
          Value: BGENERAL
        - Key: DEPARTMENT
          Value: DSO
        - Key: SERVICE_TYPE
          Value: VPC
        - Key: CATEGORY
          Value: NETWORKING
        - Key: RESPONSABLE
          Value: IPIC

  SonarqubeSecurityGroupEgressTCPAll:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref SonarqubeSecurityGroup
      IpProtocol: -1
      CidrIp: 0.0.0.0/0

Outputs:
  SonarqubeSecurityGroup:
    Description: Sonarqube Private Security Group
    Value: !Ref SonarqubeSecurityGroup
    Export:
      Name: dso-ipic-networking-sonarqube-sg
